version: '3'
services:
  db:
    image: mysql:5.7.37
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_wp
      MYSQL_USER: db_user
      MYSQL_PASSWORD: Testing123!@#
      MYSQL_RANDOM_ROOT_PASSWORD: nggih
    volumes:
      - db:/var/lib/mysql
volumes:
  db: